export default {
  "id": "M8A",
  "title": {
    "ee": "Moodul M8A Mõõtetehnika ja selle kasutamine."
  },
  "questions": [
    {
      "id": "M8A-Q1",
      "text": {
        "ee": "Milline mõõteriist sisaldab horisontaal- ja vertikaalkanali võimendi?",
        "en": "Which measuring instrument contains a horizontal and vertical channel amplifier?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Oommeeter.",
            "en": "Ohmmeter"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Signaalgeneraator.",
            "en": "Signal generator"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Ostsillograaf.",
            "en": "Oscilloscope"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Ampermeeter.",
            "en": "Ammeter"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q2",
      "text": {
        "ee": "Mis tüüpi signaale on võimalik ostsillograafi abil vaadelda?",
        "en": "What types of signals can be observed using an oscilloscope?"
      },
      "answers": [
        {
          "correct": true,
          "text": {
            "ee": "Suvalisi ajast sõltuvaid signaale instrumendi sagedusriba piires.",
            "en": "Any time-dependent signals within the instrument's frequency band"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Rahvusvahelisi laevade lipusignaale.",
            "en": "International ship flag signals"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Ookeanilaevade blinkersignaale.",
            "en": "Blinker signals of ocean-going ships"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Ioniseeritud atmosfäärikihtide poolt genereeritavaid signaale.",
            "en": "Aid signals generated by ionized atmospheric layers"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q3",
      "text": {
        "ee": "Mis seade on ostsillograaf?",
        "en": "What device is an oscillograph?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Seade,mis näitab antenni kiirgustakistust.",
            "en": "A device that indicates the radiation resistance of an antenna"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Seade,mis näitab antenni toiteliini seisulaine tegurit.",
            "en": "A device that indicates the standing wave factor of an antenna feed line"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Seade, mis võimaldab uurida kuvaril signaalide lainekuju.",
            "en": "A device that allows you to examine the waveform of signals on a display"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Vooluringi takistust mõõtev seade.",
            "en": "A device that measures the resistance of a circuit"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q4",
      "text": {
        "ee": "Mis võib põhjustada ostsillograafi kineskoobi luminofoori riknemise?",
        "en": "What can cause the phosphor in an oscilloscopes kinescope to fail?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Vertikaalkanali võimendi ületüürimine.",
            "en": "Overdriving the vertical channel amplifier"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Liig suur heleduse säting.",
            "en": "Brightness setting too high"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Kiire ebaõige fokuseerimine.",
            "en": "Fast incorrect focusing"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Kineskoobi kallutuselektroodide vahetu ühendamine skeemi.",
            "en": "Direct connection of the kinescope tilt electrodes to the diagram"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q5",
      "text": {
        "ee": "Mis seade on antenni mürasild?",
        "en": "What device is an antenna noise bridge?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Seade antenni või muu elektrilise lülituse mürateguri mõõtmiseks.",
            "en": "A device for measuring the noise figure of an antenna or other electrical circuit"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Seade antenni või muu elektrilise lülituse impedantsi mõõtmiseks.",
            "en": "A device for measuring the impedance of an antenna or other electrical circuit"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Seade vastuvõtjas esineva müra hävitamiseks.",
            "en": "A device for eliminating noise in a receiver"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Seade Päikese raadiokiirguse mõõtmiseks.",
            "en": "A device for measuring solar radio radiation"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q6",
      "text": {
        "ee": "Kuhu ühendatakse antenni mürasild?",
        "en": "Where is the antenna noise bridge connected?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Seade ühendatakse antenni toitepunkti ja müra suurus loetakse seadme skaalalt.",
            "en": "The device is connected to the antenna power point and the noise level is read from the device scale"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Seade ühendatakse saatja ja antenni vahele ning häälestatakse minimaalse seisulaine teguri saavutamiseni.",
            "en": "The device is connected between the transmitter and the antenna and tuned until the minimum standing wave factor is achieved"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Seade ühendatakse vastuvõtja ja tundmatu impedantsiga lülituse vahele ning häälestatakse minimaalse müra saavutamiseni.",
            "en": "The device is connected between the receiver and a circuit with unknown impedance and tuned to achieve minimum noise"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Seade ühendatakse antenni ja antenni sobituslülituse vahele ning häälestatakse minimaalse seisulaine teguri saavutamiseni.",
            "en": "The device is connected between the antenna and the antenna matching circuit and tuned until the minimum standing wave factor is achieved"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q7",
      "text": {
        "ee": "Mis seade on väljatugevuse mõõtja?",
        "en": "What device is a field strength meter?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Seade, mis mõõdab seisulaine tegurit antenni toiteliinis.",
            "en": "A device that measures the standing wave factor in an antenna feed line"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Seade modulatsioonisügavuse määramiseks saatja väljundis.",
            "en": "A device for determining the modulation depth at the transmitter output"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Seade kõrgsagedussignaali suhtelise võimsuse mõõtmiseks.",
            "en": "A device for measuring the relative power of a high-frequency signal"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Seade saatja keskmise väljundvõimsuse suurendamiseks.",
            "en": "A device for increasing the average output power of a transmitter"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q8",
      "text": {
        "ee": "Kui palju tuleb suurendada saatja väljundvõimsusust,et saatja läheduses asuva vastuvõtja S-meetri näit suureneks S8-lt S9-ni ?",
        "en": "How much must the transmitter output power be increased so that the S-meter reading of the receiver located near the transmitter increases from S8 to S9?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Ligikaudu kaks korda",
            "en": "Approximately two times"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Ligikaudu kolm korda",
            "en": "Approximately three times"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Ligikaudu neli korda.",
            "en": "Approximately four times"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Ligikaudu viis korda",
            "en": "Approximatley 5 times"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q9",
      "text": {
        "ee": "Milline on kõige sobivam lihtne instrument antenni kiirguse suunadiagrammi määramiseks horisontaaltasapinnas?",
        "en": "What is the most suitable simple instrument for determining the radiation pattern of an antenna in the horizontal plane?"
      },
      "answers": [
        {
          "correct": true,
          "text": {
            "ee": "Väljatugevuse mõõtja.",
            "en": "Field strength meter"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Antenni mürasild.",
            "en": "Antenna noise bridge"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Tester.",
            "en": "Tester"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Transmatch.",
            "en": "Transmatch"
          }
        }
      ],
      "info": []
    },
    {
      "id": "M8A-Q10",
      "text": {
        "ee": "Millist seadet saab kasutada saatja väljundsignaalis esinevate intermodulatsiooni-moonutustes tekitatud parasiitsignaalide uurimiseks?",
        "en": "What device can be used to study parasitic signals caused by intermodulation distortion in the transmitter output signal?"
      },
      "answers": [
        {
          "correct": false,
          "text": {
            "ee": "Vattmeeter.",
            "en": "Wattmeter"
          }
        },
        {
          "correct": true,
          "text": {
            "ee": "Spektrianalüsaator.",
            "en": "Spectrum analyser"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Loogikaskeemide analüsaator.",
            "en": "Logic circuit analyzer"
          }
        },
        {
          "correct": false,
          "text": {
            "ee": "Mäluga reflektomeeter.",
            "en": "Reflectometer with memory"
          }
        }
      ],
      "info": []
    }
  ]
}