import * as ctx from "./ExamContext";
import { ExamStateImpl } from "./ExamStateImpl";


export declare namespace ExamApi {
  
  export interface ErauSubject {
    id: string;
    tk?: string; // autogenerated
    title: string;
    questions: ErauQuestion[]
  }
  
  export interface ErauQuestion {
    id: string;
    tk?: string; // autogenerated 
    text: string;
    enText?: string;
    info: string;
    answers: ErauAnswer[];
  }
  export interface ErauAnswer {
    tk?: string; // autogenerated
    text: string; 
    correct: boolean
  }


  export interface Subject {
    tk: string;
    id: string;
    title: string;
    questions: Question[]
  }
  export interface Question {
    tk: string;
    id: string;
    subjectId: string;
    text: string;
    enText?: string;
    info: string;
    answers: Answer[];
    correctAnswer: string | undefined;
    userAnswer: string | undefined;
    isAnsweredCorrectly: boolean | undefined;
    isAnswered: boolean;
  }
  export interface Answer {
    tk: string;
    questionId: string;
    subjectId: string;
    text: string;
    correct: boolean;
    isAnswered: boolean;
    isQuestionAnswered: boolean  | undefined;
    isQuestionAnsweredCorrectly: boolean | undefined;
  }

  export interface Questionnaire {
    subjects: Record<string, Subject>; 
    questions: Record<string, Question>;
    answers: Record<string, Answer>;
  }

  export interface ExamState {
    questionnaire: Questionnaire;
    selectAnswer(answerTk: string): ExamState;
    suffle(nextNQuestions: number): ExamState;
    reset(): ExamState;
    all(): ExamState;
    stats: { 
      perc: string;
      total: number;
      correct: number;
    }
  }

  export interface ExamContextType {
    value: ExamState;
    selectAnswer(answerTk: string): void;
    shuffle(nextNQuestions: number): void;
    reset(): void;
    all(): void;
  }
}

export namespace ExamApi {
  export const ExamProvider = ctx.ExamProvider;
  export const useExam = ctx.useExam;
  export const getInstance = (source: ErauSubject[]): ExamState => new ExamStateImpl({ source });
}